# Force Publish HA Birth Message
- id: zigbee_publish_birth_message
  alias: Zigbee Publish MQTT Birth Message
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: '10'
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/bridge/state'
        payload: 'online'

# Close blinds at night
- alias: "Close covers at night"
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:30:00"
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - group.blinds_living_room
        - group.blinds_office
        
# Open blinds in the morning
- alias: "Open blinds in the morning"
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:00:00"
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - group.blinds_living_room
        - group.blinds_office