homeassistant:
  name: Home
  latitude: !env_var HASS_SECRET_LATITUDE
  longitude: !env_var HASS_SECRET_LONGITUDE
  elevation: !env_var HASS_SECRET_ELEVATION
  unit_system: metric
  time_zone: Europe/Paris
  country: FR
  internal_url: "http://localhost:8123"
  external_url: !env_var HASS_SECRET_URL

http:
  server_host: 0.0.0.0
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.8.0/22
  - 10.10.0.0/24
  - 10.95.0.0/16

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !env_var HASS_SECRET_DB_URL
  purge_keep_days: 90
   
prometheus:
  namespace: hass
  filter:
    include_domains:
      - sensor
 
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module

frontend:
  themes: !include_dir_merge_named themes

rflink:
  port: "/dev/ttyUSB0"

# logger:
#   default: error
#   logs:
#     rflink: debug
#     homeassistant.components.rflink: debug

cover:
 - platform: rflink
   devices:
     RTS_0A0A0A_0:
       name: blind_office_1
 - platform: rflink
   devices:
     RTS_0B0B0B_0:
       name: blind_office_2
 - platform: rflink
   devices:
     RTS_0C0C0C_0:
       name: blind_living_room_1
 - platform: rflink
   devices:
     RTS_0D0D0D_0:
       name: blind_living_room_2
 - platform: group
   name: blinds_living_room
   entities:
     - cover.blind_living_room_1
     - cover.blind_living_room_2