---
title: Dashboard
views:
  - title: Living Room
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:button-card'
            color_type: label-card
            color: rgb(73, 77, 100)
            name: Home Cinema
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                name: No Lights
                icon: mdi:theater
                color: rgb(138, 173, 244)
                show_state: false
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id:
                      - script.theater_mode_no_lights
                      - script.home_cinema_power_on
              - type: custom:button-card
                name: Lights
                icon: mdi:theater
                color: rgb(238, 212, 159)
                show_state: false
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id:
                      - script.theater_mode_lights
                      - script.home_cinema_power_on
              - type: custom:button-card
                name: "Audio"
                icon: mdi:audio-video
                color: rgb(138, 173, 244)
                show_state: false
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id:
                      - script.home_cinema_audio_only_power_on
              - type: custom:button-card
                name: "OFF"
                icon: mdi:power-plug-off
                color: rgb(67, 73, 75)
                show_state: false
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.home_cinema_power_off
          - type: 'custom:button-card'
            color_type: label-card
            color: rgb(73, 77, 100)
            name: Denon AVR X1300W
          - type: horizontal-stack
            cards:
              - type: custom:mini-media-player
                entity: media_player.denon_avr_x1300w
                group: false
                volume_stateless: false
                toggle_power: false
                artwork: none
                source: false
                hide:
                  name: true
                  # source: true
                  power: true
                shortcuts:
                  columns: 4
                  buttons:
                    - type: source
                      id: Kodi
                      name: Kodi
                    - type: source
                      id: piCorePlayer
                      name: piCorePlayer
                    - type: source
                      id: Switch
                      name: Switch
          - type: 'custom:button-card'
            color_type: label-card
            color: rgb(73, 77, 100)
            name: Blinds
          - type: horizontal-stack
            cards:
              - type: entities
                id: card_blinds
                entities:
                  - entity: cover.blind_living_room_1
                    name: Living Room - Left
                  - entity: cover.blind_living_room_2
                    name: Living Room - Right
                  - entity: cover.blind_office_2
                    name: Office
  - title: Sensors
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Bedroom 1
            line_color: var(--accent-color)
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_bedroom_temperature
          - type: custom:mini-graph-card
            name: Bedroom 1
            line_color: blue
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_bedroom_humidity
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Living room
            line_color: var(--accent-color)
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_living_room_temperature
          - type: custom:mini-graph-card
            name: Living room
            line_color: blue
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_living_room_humidity
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Office
            line_color: var(--accent-color)
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_office_temperature
          - type: custom:mini-graph-card
            name: Office
            line_color: blue
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_office_humidity
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Bedroom 2
            line_color: var(--accent-color)
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_hallway_temperature
          - type: custom:mini-graph-card
            name: Bedroom 2
            line_color: blue
            aggregate_func: last
            hour24: true
            entities:
            - sensor.temperature_hallway_humidity
